// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtaiMeKUiayP-DCyc12cvZG243Lq6cKnk',
    appId: '1:510219616867:web:PLACEHOLDER',
    messagingSenderId: '510219616867',
    projectId: 'kivago',
    authDomain: 'kivago.firebaseapp.com',
    storageBucket: 'kivago.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtaiMeKUiayP-DCyc12cvZG243Lq6cKnk',
    appId: '1:510219616867:android:d42b242fccc46f55aaae56',
    messagingSenderId: '510219616867',
    projectId: 'kivago',
    storageBucket: 'kivago.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtaiMeKUiayP-DCyc12cvZG243Lq6cKnk',
    appId: '1:510219616867:ios:PLACEHOLDER',
    messagingSenderId: '510219616867',
    projectId: 'kivago',
    storageBucket: 'kivago.firebasestorage.app',
    iosBundleId: 'com.android.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtaiMeKUiayP-DCyc12cvZG243Lq6cKnk',
    appId: '1:510219616867:ios:PLACEHOLDER',
    messagingSenderId: '510219616867',
    projectId: 'kivago',
    storageBucket: 'kivago.firebasestorage.app',
    iosBundleId: 'com.android.application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtaiMeKUiayP-DCyc12cvZG243Lq6cKnk',
    appId: '1:510219616867:web:PLACEHOLDER',
    messagingSenderId: '510219616867',
    projectId: 'kivago',
    storageBucket: 'kivago.firebasestorage.app',
  );
}

